
export enum GameState {
    GAME_STARTED,
    FIRST_CARDS_HANDED_OUT,
    ALL_CARDS_HANDED_OUT,
    WAITING_FOR_EXCHANGE,
    CARDS_EXCHANGED,
    ROUND_STARTED,
    ROUND_ENDED,
    GAME_ENDED,
  }
